package views;

import modelo.Usuario;
import hospital.view.controller.ListaUsuariosController;
import hospital.view.controller.TableModelUsuario;
import java.awt.event.ActionListener;

/**
 *
 * @author 78522
 */
public class ListaUsuarios extends javax.swing.JFrame implements ListaUsuariosController.Display {

    private final ListaUsuariosController controller;

    /**
     * Creates new form AdmUsuario
     */
    public ListaUsuarios() {
        initComponents();
        controller = new ListaUsuariosController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdicionar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Usuários");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        btnAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/add182.png"))); // NOI18N
        jPanel2.add(btnAdicionar);

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/pencil117.png"))); // NOI18N
        jPanel2.add(btnEditar);

        btnRemover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/cross108.png"))); // NOI18N
        jPanel2.add(btnRemover);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAcaoAdd(ActionListener listener) {
        btnAdicionar.addActionListener(listener);
    }

    @Override
    public void setAcaoEdit(ActionListener listener) {
        btnEditar.addActionListener(listener);
    }

    @Override
    public void setAcaoRemove(ActionListener listener) {
        btnRemover.addActionListener(listener);
    }

    @Override
    public void configurarTabela(TableModelUsuario model) {
        jTable1.setModel(model);
    }

    @Override
    public Usuario getSelected() {
        return jTable1.getSelectedRowCount() > 0 ? ((TableModelUsuario) jTable1.getModel()).getRow(jTable1.convertRowIndexToModel(jTable1.getSelectedRow())) : null;
    }
}
