/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package caixaeletronico;

/**
 *
 * @author abb
 */
public class JFMeuCaixa extends javax.swing.JFrame {
    int Total, qtd100,qtd50,qtd20,qtd10,qtd5,qtd2;
    
    /**
     * Creates new form JFMeuCaixa
     */
    public JFMeuCaixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLTituloValor = new javax.swing.JLabel();
        qtdDinheiro = new javax.swing.JTextField();
        Notas100 = new javax.swing.JLabel();
        Notas50 = new javax.swing.JLabel();
        Notas20 = new javax.swing.JLabel();
        Notas10 = new javax.swing.JLabel();
        Notas5 = new javax.swing.JLabel();
        Notas2 = new javax.swing.JLabel();
        jBSair = new javax.swing.JButton();
        CalcularNotas = new javax.swing.JButton();
        LimparForm = new javax.swing.JButton();
        qtdNotas100 = new javax.swing.JLabel();
        QtdNotas50 = new javax.swing.JLabel();
        QtdNotas20 = new javax.swing.JLabel();
        QtdNotas10 = new javax.swing.JLabel();
        QtdNotas5 = new javax.swing.JLabel();
        QtdNotas2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CAIXA ELETRÔNICA - V.001 ABB");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(204, 255, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLTituloValor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLTituloValor.setText("VALOR:");
        getContentPane().add(jLTituloValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 11, 114, 50));

        qtdDinheiro.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        qtdDinheiro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(qtdDinheiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 11, 159, -1));

        Notas100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixaeletronico/100reais.jpg"))); // NOI18N
        getContentPane().add(Notas100, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 81, -1, -1));

        Notas50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixaeletronico/50reais.jpg"))); // NOI18N
        getContentPane().add(Notas50, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 79, -1, -1));

        Notas20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixaeletronico/20reais.jpg"))); // NOI18N
        getContentPane().add(Notas20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 81, -1, -1));

        Notas10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixaeletronico/10reais.jpg"))); // NOI18N
        getContentPane().add(Notas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 237, -1, 73));

        Notas5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixaeletronico/5reais.jpg"))); // NOI18N
        getContentPane().add(Notas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 237, 151, 73));

        Notas2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/caixaeletronico/Nota1Real.png"))); // NOI18N
        getContentPane().add(Notas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 240, 130, 70));

        jBSair.setText("SAIR");
        jBSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSairActionPerformed(evt);
            }
        });
        getContentPane().add(jBSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(318, 410, 121, 32));

        CalcularNotas.setText("CALCULAR NOTAS");
        CalcularNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularNotasActionPerformed(evt);
            }
        });
        getContentPane().add(CalcularNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 410, -1, 32));

        LimparForm.setText("LIMPAR");
        LimparForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparFormActionPerformed(evt);
            }
        });
        getContentPane().add(LimparForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 410, 121, 32));

        qtdNotas100.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        qtdNotas100.setForeground(new java.awt.Color(0, 0, 204));
        qtdNotas100.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdNotas100.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(qtdNotas100, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 159, 130, 58));

        QtdNotas50.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        QtdNotas50.setForeground(new java.awt.Color(255, 0, 51));
        QtdNotas50.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QtdNotas50.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(QtdNotas50, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 159, 130, 58));

        QtdNotas20.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        QtdNotas20.setForeground(new java.awt.Color(102, 0, 255));
        QtdNotas20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QtdNotas20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(QtdNotas20, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 158, 130, 59));

        QtdNotas10.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        QtdNotas10.setForeground(new java.awt.Color(255, 0, 153));
        QtdNotas10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QtdNotas10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(QtdNotas10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 321, 130, 59));

        QtdNotas5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        QtdNotas5.setForeground(new java.awt.Color(204, 0, 51));
        QtdNotas5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QtdNotas5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(QtdNotas5, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 321, 130, 59));

        QtdNotas2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        QtdNotas2.setForeground(new java.awt.Color(204, 0, 51));
        QtdNotas2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        QtdNotas2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(QtdNotas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 321, 130, 59));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBSairActionPerformed

    private void LimparFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparFormActionPerformed
        // TODO add your handling code here:
        qtdDinheiro.setText("");
        qtdNotas100.setText(null);
        QtdNotas50.setText(null);
        QtdNotas20.setText(null);
        QtdNotas10.setText(null);
        QtdNotas5.setText(null);
        QtdNotas2.setText(null);
    }//GEN-LAST:event_LimparFormActionPerformed

    private void CalcularNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularNotasActionPerformed
        // TODO add your handling code here:        

        Total   = Integer.valueOf(qtdDinheiro.getText());
        qtd100  = Total /100;
        qtd50   = (Total - qtd100*100)/50;
        qtd20   = (Total - qtd100*100 - qtd50*50)/20;
        qtd10   = (Total - (qtd100*100) - (qtd50*50)-(qtd20*20))/10;
        qtd5    = (Total - (qtd100*100) - (qtd50*50)-(qtd20*20)- (qtd10*10))/5;
        qtd2    = (Total - (qtd100*100) - (qtd50*50)-(qtd20*20)- (qtd10*10)- (qtd5*5))/1;
                
        qtdNotas100.setText(String.valueOf(qtd100));
        QtdNotas50.setText(String.valueOf(qtd50));
        QtdNotas20.setText(String.valueOf(qtd20));
        QtdNotas10.setText(String.valueOf(qtd10));
        QtdNotas5.setText(String.valueOf(qtd5));
        QtdNotas2.setText(String.valueOf(qtd2));
    }//GEN-LAST:event_CalcularNotasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMeuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMeuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMeuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMeuCaixa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFMeuCaixa().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcularNotas;
    private javax.swing.JButton LimparForm;
    private javax.swing.JLabel Notas10;
    private javax.swing.JLabel Notas100;
    private javax.swing.JLabel Notas2;
    private javax.swing.JLabel Notas20;
    private javax.swing.JLabel Notas5;
    private javax.swing.JLabel Notas50;
    private javax.swing.JLabel QtdNotas10;
    private javax.swing.JLabel QtdNotas2;
    private javax.swing.JLabel QtdNotas20;
    private javax.swing.JLabel QtdNotas5;
    private javax.swing.JLabel QtdNotas50;
    private javax.swing.JButton jBSair;
    private javax.swing.JLabel jLTituloValor;
    private javax.swing.JTextField qtdDinheiro;
    private javax.swing.JLabel qtdNotas100;
    // End of variables declaration//GEN-END:variables
}
