/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.ControleLista;
import dados.Usuario;
import java.awt.event.ActionListener;
import tabela.UsuarioTableModel;

/**
 *
 * @author 88178
 */
public class AdmUsuario extends javax.swing.JFrame implements ControleLista.Display {

    private ControleLista controlador;

    /**
     * Creates new form AdmUsuario
     */
    public AdmUsuario() {
        initComponents();
        controlador = new ControleLista(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        btnCadastrar.setText("Cadastrar");
        jPanel4.add(btnCadastrar);

        btnRemover.setText("Remover");
        jPanel4.add(btnRemover);

        btnVoltar.setText("Voltar ao menu");
        jPanel4.add(btnVoltar);

        getContentPane().add(jPanel4, java.awt.BorderLayout.PAGE_END);

        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableUsuario);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.PAGE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableUsuario;
    // End of variables declaration//GEN-END:variables

    @Override
    public void configurarTabela(UsuarioTableModel model) {
        jTableUsuario.setModel(model);
    }

    @Override
    public void addAcaoCadastrar(ActionListener listener) {
        btnCadastrar.addActionListener(listener);
    }

    @Override
    public void addAcaoRemover(ActionListener listener) {
        btnRemover.addActionListener(listener);
    }

    @Override
    public void addAcaoVoltar(ActionListener listener) {
        btnVoltar.addActionListener(listener);
    }

    @Override
    public void fecharTela() {
        dispose();
    }

    @Override
    public Usuario getSelecionado() {
        if (jTableUsuario.getSelectedRowCount() > 0) {
            UsuarioTableModel modelo = (UsuarioTableModel) jTableUsuario.getModel();
            int index = jTableUsuario.getSelectedRow();
            int indexConvertido = jTableUsuario.convertRowIndexToModel(index);
            Usuario user = modelo.getRow(indexConvertido);
            return user;
        }
        return null;
    }
}
