/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import controle.ControleCadastroUsuario;
import estado.Tipo;
import java.awt.event.ActionListener;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author 88178
 */
public class CadastroUsuario extends javax.swing.JFrame implements ControleCadastroUsuario.Display{

    private ControleCadastroUsuario controlador;
    
    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario(ActionListener listener) {       
        initComponents();
        controlador = new ControleCadastroUsuario(this, listener);             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCredencial = new javax.swing.JComboBox();
        jButtonExit = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jPasswordFieldSenha = new javax.swing.JPasswordField();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Login :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        getContentPane().add(jTextFieldLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 240, -1));

        jLabel2.setText("Senha :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel4.setText("Credencial :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(jComboBoxCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 110, -1));

        jButtonExit.setText("Cancelar");
        getContentPane().add(jButtonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jButtonSalvar.setText("Salvar");
        getContentPane().add(jButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, -1));

        jPasswordFieldSenha.setText("jPasswordField1");
        getContentPane().add(jPasswordFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 240, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxCredencial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldLogin;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getLogin() {
        return jTextFieldLogin.getText();
    }

    @Override
    public String getSenha() {
       return String.valueOf(jPasswordFieldSenha.getPassword());
    }

    @Override
    public Tipo getCredencial() {
       return (Tipo)jComboBoxCredencial.getSelectedItem();
    }

    @Override
    public void addAcaoSalvar(ActionListener listener) {
        jButtonSalvar.addActionListener(listener);
    }

    @Override
    public void addAcaoCancelar(ActionListener listener) {
       jButtonExit.addActionListener(listener);
    }

    @Override
    public void fecharTela() {
        dispose();
    }

    @Override
    public void configurarTipo(DefaultComboBoxModel modelo) {
        jComboBoxCredencial.setModel(modelo);
    }
}
