package hospital.views;

import modelo.Visitante;
import hospital.view.controller.ListaVisitantesController;
import hospital.view.controller.TableModelVisitante;
import java.awt.event.ActionListener;

/**
 *
 * @author 78522
 */
public class ListaVisitantes extends javax.swing.JFrame implements ListaVisitantesController.Display {

    private final ListaVisitantesController controller;

    /**
     * Creates new form AdmUsuario
     */
    public ListaVisitantes() {
        initComponents();
        controller = new ListaVisitantesController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnEntrada = new javax.swing.JButton();
        btnEspera = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Visitantes");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        btnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/pointing6.png"))); // NOI18N
        btnEntrada.setText("Entrada");
        jPanel1.add(btnEntrada);

        btnEspera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/waiting2.png"))); // NOI18N
        btnEspera.setText("Espera");
        jPanel1.add(btnEspera);

        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/right arrow62 (1).png"))); // NOI18N
        btnSaida.setText("Saída");
        jPanel1.add(btnSaida);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/add182.png"))); // NOI18N
        jPanel3.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/pencil117.png"))); // NOI18N
        jPanel3.add(btnEdit);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/cross108.png"))); // NOI18N
        jPanel3.add(btnRemove);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JButton btnEspera;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSaida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAcaoAdd(ActionListener listener) {
        btnAdd.addActionListener(listener);
    }

    @Override
    public void setAcaoEdit(ActionListener listener) {
        btnEdit.addActionListener(listener);
    }

    @Override
    public void setAcaoRemove(ActionListener listener) {
        btnRemove.addActionListener(listener);
    }

    @Override
    public void setAcaoEntrada(ActionListener listener) {
        btnEntrada.addActionListener(listener);
    }

    @Override
    public void setAcaoEspera(ActionListener listener) {
        btnEspera.addActionListener(listener);
    }

    @Override
    public void setAcaoSaida(ActionListener listener) {
        btnSaida.addActionListener(listener);
    }

    @Override
    public void configurarTabela(TableModelVisitante model) {
        jTable1.setModel(model);
    }

    @Override
    public Visitante getSelected() {
        return jTable1.getSelectedRowCount() > 0 ? ((TableModelVisitante) jTable1.getModel()).getRow(jTable1.convertRowIndexToModel(jTable1.getSelectedRow())) : null;
    }

}
