package hospital.views;

import modelo.Paciente;
import hospital.view.controller.ListaPacientesController;
import hospital.view.controller.TableModelPaciente;
import java.awt.event.ActionListener;

/**
 *
 * @author 78522
 */
public class ListaPacientes extends javax.swing.JFrame implements ListaPacientesController.Display {

    private final ListaPacientesController controller;

    /**
     * Creates new form AdmUsuario
     */
    public ListaPacientes() {
        initComponents();
        controller = new ListaPacientesController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelBotoes = new javax.swing.JPanel();
        btnSaida = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Pacientes UTI");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBotoes.setLayout(new java.awt.GridLayout(1, 0));

        btnSaida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/right arrow62 (1).png"))); // NOI18N
        btnSaida.setText("Registrar Saída");
        panelBotoes.add(btnSaida);

        getContentPane().add(panelBotoes, java.awt.BorderLayout.PAGE_END);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/add182.png"))); // NOI18N
        jPanel2.add(btnAdd);

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/pencil117.png"))); // NOI18N
        jPanel2.add(btnEdit);

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/telalogin/imagens/remove11.png"))); // NOI18N
        jPanel2.add(btnRemove);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSaida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelBotoes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAcaoAdd(ActionListener listener) {
        btnAdd.addActionListener(listener);
    }

    @Override
    public void setAcaoEdit(ActionListener listener) {
        btnEdit.addActionListener(listener);
    }

    @Override
    public void setAcaoRemove(ActionListener listener) {
        btnRemove.addActionListener(listener);
    }

    @Override
    public void setAcaoSaida(ActionListener listener) {
        btnSaida.addActionListener(listener);
    }

    @Override
    public void configurarTabela(TableModelPaciente model) {
        jTable1.setModel(model);
    }

    @Override
    public Paciente getSelected() {
        return jTable1.getSelectedRowCount() > 0 ? ((TableModelPaciente) jTable1.getModel()).getRow(jTable1.convertRowIndexToModel(jTable1.getSelectedRow())) : null;
    }

}
