/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.oficinaV2.visualizacao;

import br.com.oficinaV2.presenter.TelaPrincipalPresenter;
import java.awt.event.ActionListener;

/**
 *
 * @author felipe.oliveira
 */
public class TelaPrincipal extends javax.swing.JFrame  implements TelaPrincipalPresenter.Display{

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiVeiculoListar = new javax.swing.JMenuItem();
        jmiVeiculoNovo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiClienteListar = new javax.swing.JMenuItem();
        jmiClienteNovo = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiOrdemServicoListar = new javax.swing.JMenuItem();
        jmiOrdemServicoNovo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Veiculo");

        jmiVeiculoListar.setText("Listar");
        jMenu1.add(jmiVeiculoListar);

        jmiVeiculoNovo.setText("Novo");
        jMenu1.add(jmiVeiculoNovo);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cliente");

        jmiClienteListar.setText("Listar");
        jMenu2.add(jmiClienteListar);

        jmiClienteNovo.setText("Novo");
        jMenu2.add(jmiClienteNovo);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ordem de serviço");

        jmiOrdemServicoListar.setText("Listar");
        jMenu3.add(jmiOrdemServicoListar);

        jmiOrdemServicoNovo.setText("Nova");
        jMenu3.add(jmiOrdemServicoNovo);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiClienteListar;
    private javax.swing.JMenuItem jmiClienteNovo;
    private javax.swing.JMenuItem jmiOrdemServicoListar;
    private javax.swing.JMenuItem jmiOrdemServicoNovo;
    private javax.swing.JMenuItem jmiVeiculoListar;
    private javax.swing.JMenuItem jmiVeiculoNovo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAcaoListarVeiculo(ActionListener listener) {
        jmiVeiculoListar.addActionListener(listener);
    }

    @Override
    public void setAcaoNovoVeiculo(ActionListener listener) {
        jmiVeiculoNovo.addActionListener(listener);
    }

    @Override
    public void setAcaoListarCliente(ActionListener listener) {
        jmiClienteListar.addActionListener(listener);
    }

    @Override
    public void setAcaoNovoCliente(ActionListener listener) {
        jmiClienteNovo.addActionListener(listener);
    }

    @Override
    public void setAcaoListarOrdemServico(ActionListener listener) {
        jmiOrdemServicoListar.addActionListener(listener);
    }

    @Override
    public void setAcaoNovaOrdemServico(ActionListener listener) {
        jmiOrdemServicoNovo.addActionListener(listener);
    }

    @Override
    public void mostrar() {
        setVisible(true);
    }

    @Override
    public void esconder() {
        setVisible(false);
    }
}
