/*
 * EntityIntroductionPanel.java
 *
 * Created on February 2, 2006, 2:54 PM
 */

package br.com.invnautico.core.gui.introduction;

import java.io.IOException;
import java.net.URL;
import javax.swing.JEditorPane;

/**
 *
 * @author  vsenger
 */
public class GenericIntroductionPanel extends javax.swing.JPanel {
    private String entidade;
    private String titulo;
    private String imagemTop;
    public void loadPanel() {
        URL helpText = GenericIntroductionPanel.class.getResource("/" + entidade + ".html");
        try {
            this.textHelp.setPage(helpText);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        
    }
    /** Creates new form EntityIntroductionPanel */
    public GenericIntroductionPanel() {
        initComponents();
    }
    
    public String getEntidade() {
        return entidade;
    }
    
    public void setEntidade(String entidade) {
        this.entidade = entidade;
        loadPanel();
        labelTitle.setText("Gestão de " + entidade);
    }
    
    public String getTitulo() {
        return titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    
    public String getImagemTop() {
        return imagemTop;
    }
    
    public void setImagemTop(String imagemTop) {
        this.imagemTop = imagemTop;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        labelImageTop = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textHelp = new javax.swing.JEditorPane();

        jScrollPane1.setBorder(null);
        textHelp.setBorder(null);
        textHelp.setEditable(false);
        jScrollPane1.setViewportView(textHelp);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(labelTitle, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelImageTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(labelTitle, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(labelImageTop, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelImageTop;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JEditorPane textHelp;
    // End of variables declaration//GEN-END:variables
    
}
