package br.com.tiagodws.hospital.view;

import br.com.tiagodws.hospital.view.controller.MenuPrincipalController;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author 78522
 */
public class Principal extends javax.swing.JFrame implements MenuPrincipalController.Display {

    private final MenuPrincipalController controller;

    /**
     * Creates new form Principal
     *
     */
    public Principal() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnVisitantes = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        miLogoff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Saúde");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnVisitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tiagodws/hospital/resources/two206.png"))); // NOI18N
        btnVisitantes.setText("Visitantes");
        btnVisitantes.setEnabled(false);
        jPanel2.add(btnVisitantes);

        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tiagodws/hospital/resources/health11.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setEnabled(false);
        jPanel2.add(btnPacientes);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tiagodws/hospital/resources/user2.png"))); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setEnabled(false);
        jPanel2.add(btnUsuarios);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/tiagodws/hospital/resources/Philips.png"))); // NOI18N

        menuArquivo.setText("Arquivo");

        miLogoff.setText("Trocar Usuário");
        menuArquivo.add(miLogoff);

        jMenuBar1.add(menuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVisitantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem miLogoff;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAcaoMenuPacientes(ActionListener listener) {
        btnPacientes.addActionListener(listener);
    }

    @Override
    public void setAcaoMenuVisitantes(ActionListener listener) {
        btnVisitantes.addActionListener(listener);
    }

    @Override
    public void setAcaoMenuUsuarios(ActionListener listener) {
        btnUsuarios.addActionListener(listener);
    }

    @Override
    public void setAcaoLogoff(ActionListener listener) {
        miLogoff.addActionListener(listener);
    }

    @Override
    public void setAcessoBtnPacientes(boolean acesso) {
        btnPacientes.setEnabled(acesso);
    }

    @Override
    public void setAcessoBtnVisitantes(boolean acesso) {
        btnVisitantes.setEnabled(acesso);
    }

    @Override
    public void setAcessoBtnUsuarios(boolean acesso) {
        btnUsuarios.setEnabled(acesso);
    }

    @Override
    public void fechar() {
        dispose();
    }

}
