/*
 * PanelItemPedido.java
 *
 * Created on 8 de Abril de 2006, 10:53
 */

package br.org.soujava.teleentrega.gui;

import br.org.soujava.teleentrega.model.Item;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;

/**
 *
 * @author  vsenger
 */
public class PanelItemPedido extends javax.swing.JDialog {
  private Item entity;
  /** Creates new form PanelItemPedido */
  public PanelItemPedido(Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    
  }
  public void center() {
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = this.getSize();
    if (frameSize.height > screenSize.height) {
      frameSize.height = screenSize.height;
    }
    if (frameSize.width > screenSize.width) {
      frameSize.width = screenSize.width;
    }
    setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    textDescricao = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    textQtd = new javax.swing.JTextField();
    textPreco = new javax.swing.JTextField();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();
    jLabel4 = new javax.swing.JLabel();
    textTotal = new javax.swing.JTextField();

    jLabel1.setText("Descri\u00e7\u00e3o");

    jLabel2.setText("Qtd.");

    jLabel3.setText("Pre\u00e7o");

    textQtd.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
      public void propertyChange(java.beans.PropertyChangeEvent evt) {
        textQtdPropertyChange(evt);
      }
    });
    textQtd.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        textQtdFocusLost(evt);
      }
    });

    textPreco.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        textPrecoFocusLost(evt);
      }
    });

    jButton1.setText("Cancelar");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("OK");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    jLabel4.setText("Total");

    textTotal.setEditable(false);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(textDescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
              .add(jLabel1))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel2)
              .add(textQtd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(layout.createSequentialGroup()
                .add(textPreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(textTotal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
              .add(layout.createSequentialGroup()
                .add(jLabel3)
                .add(51, 51, 51)
                .add(jLabel4))))
          .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .add(jButton2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jButton1)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(jLabel2)
          .add(jLabel3)
          .add(jLabel4))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(textDescricao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(textQtd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(textPreco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(textTotal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 17, Short.MAX_VALUE)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jButton1)
          .add(jButton2))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  
  private void textPrecoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textPrecoFocusLost
// TODO add your handling code here:
    updateTotal();
  }//GEN-LAST:event_textPrecoFocusLost
  
  private void textQtdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textQtdFocusLost
// TODO add your handling code here:
    updateTotal();
  }//GEN-LAST:event_textQtdFocusLost
  
  private void textQtdPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_textQtdPropertyChange
// TODO add your handling code here:
    
  }//GEN-LAST:event_textQtdPropertyChange
  
  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    entity = null;
    dispose();
  }//GEN-LAST:event_jButton1ActionPerformed
  
  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    this.dispose();
  }//GEN-LAST:event_jButton2ActionPerformed
  public void bind(Item item) {
    entity = item;
    this.textDescricao.setText(item.getDescricao());
    this.textQtd.setText("" + item.getQuantidade());
    this.textPreco.setText("" + item.getValor());
    updateTotal();
  }
  public Item unbind() {
    if(entity==null) return null;
    entity.setDescricao(textDescricao.getText());
    entity.setValor(Double.parseDouble(textPreco.getText()));
    entity.setQuantidade(Integer.parseInt(textQtd.getText()));
    return entity;
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField textDescricao;
  private javax.swing.JTextField textPreco;
  private javax.swing.JTextField textQtd;
  private javax.swing.JTextField textTotal;
  // End of variables declaration//GEN-END:variables
  public void updateTotal() {
    float f = Integer.parseInt(textQtd.getText()) * Float.parseFloat(textPreco.getText());
    this.textTotal.setText("" + f);
  }
}
