/*
 * Sobre.java
 *
 * Created on 8 de Abril de 2006, 13:12
 */

package br.org.soujava.teleentrega.gui;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author  vsenger
 */
public class Sobre extends javax.swing.JDialog {
  public static final String TEXTO =
      "Tutorial apresentado no SouJava em duas etapas " +
      "onde desenvolvemos este aplicativo ao-vivo " + 
      "com Swing, Hibernate, Java 5 e Jasper Reports." +
      "\nFavor considerar que o código não foi revisado e também " +
      "existem várias melhorias para desenvolvermos.\n\n" +
      "Sugerimos o uso da lista soujava-list para tirar dúvidas sobre este projeto.";
      
  /** Creates new form Sobre */
  public Sobre(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    this.textSobre.setText(TEXTO);
  }
  public void center() {
    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    Dimension frameSize = this.getSize();
    if (frameSize.height > screenSize.height) {
      frameSize.height = screenSize.height;
    }
    if (frameSize.width > screenSize.width) {
      frameSize.width = screenSize.width;
    }
    setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    textSobre = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    jLabel1.setText("SouJava Brasil - www.soujava.org.br");

    textSobre.setColumns(20);
    textSobre.setLineWrap(true);
    textSobre.setRows(5);
    jScrollPane1.setViewportView(textSobre);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
          .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
          .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(jLabel1)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        .addContainerGap())
    );
    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Sobre(new javax.swing.JFrame(), true).setVisible(true);
      }
    });
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextArea textSobre;
  // End of variables declaration//GEN-END:variables
  
}
