package hospital.views;

import hospital.view.controller.MenuPrincipalController;
import java.awt.Color;
import java.awt.event.ActionListener;


public class Principal extends javax.swing.JFrame implements MenuPrincipalController.Display {

    private final MenuPrincipalController controller;

    /**
     * Creates new form Principal
     *
     */
    public Principal() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        controller = new MenuPrincipalController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnPacientes = new javax.swing.JButton();
        btnVisitantes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        miLogoff = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Saúde");

        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/adm.png"))); // NOI18N
        btnUsuarios.setText("Usuários");
        btnUsuarios.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnUsuarios.setEnabled(false);
        jPanel2.add(btnUsuarios);

        btnPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Uti.png"))); // NOI18N
        btnPacientes.setText("Pacientes");
        btnPacientes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPacientes.setEnabled(false);
        jPanel2.add(btnPacientes);

        btnVisitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/visit.png"))); // NOI18N
        btnVisitantes.setText("Visitantes");
        btnVisitantes.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVisitantes.setEnabled(false);
        btnVisitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitantesActionPerformed(evt);
            }
        });
        jPanel2.add(btnVisitantes);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/philipsnovo.png"))); // NOI18N

        menuArquivo.setText("Arquivo");

        miLogoff.setText("Trocar Usuário");
        menuArquivo.add(miLogoff);

        jMenuBar1.add(menuArquivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVisitantesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPacientes;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton btnVisitantes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenuItem miLogoff;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setAcaoMenuPacientes(ActionListener listener) {
        btnPacientes.addActionListener(listener);
    }

    @Override
    public void setAcaoMenuVisitantes(ActionListener listener) {
        btnVisitantes.addActionListener(listener);
    }

    @Override
    public void setAcaoMenuUsuarios(ActionListener listener) {
        btnUsuarios.addActionListener(listener);
    }

    @Override
    public void setAcaoLogoff(ActionListener listener) {
        miLogoff.addActionListener(listener);
    }

    @Override
    public void setAcessoBtnPacientes(boolean acesso) {
        btnPacientes.setEnabled(acesso);
    }

    @Override
    public void setAcessoBtnVisitantes(boolean acesso) {
        btnVisitantes.setEnabled(acesso);
    }

    @Override
    public void setAcessoBtnUsuarios(boolean acesso) {
        btnUsuarios.setEnabled(acesso);
    }

    @Override
    public void fechar() {
        dispose();
    }

}
