package parte2.exercicio02;

import parte2.exercicio02.recurso.Fonte;
import parte2.exercicio02.recurso.Deposito;
import parte2.exercicio02.operario.OperarioKg;
import parte2.exercicio02.operario.OperarioEnergia;
import parte2.exercicio02.maquina.MaquinaGrande;
import parte2.exercicio02.maquina.MaquinaPequena;
import java.util.List;
import javax.swing.SwingWorker;
import parte2.exercicio02.maquina.Maquina;

/**
 *
 * @author 78522
 */
public class View extends javax.swing.JFrame {

    Mineradora mineradora;

    /**
     * Creates new form Teste
     *
     * @param mineradora
     */
    public View(Mineradora mineradora) {
        initComponents();
        this.mineradora = mineradora;
        update();
    }

    public final void update() {

        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                while (true) {
                    publish();
                }
            }

            @Override
            // Can safely update the GUI from this method.
            protected void process(List<Void> chunks) {
                Deposito dep = mineradora.getDeposito();
                Fonte fon = mineradora.getFonte();

                pbMinerio.setValue((int) (dep.getQtdRecurso() * 100 / dep.getQtdMaxRecurso()));

                pbMinerio.setString(Formatter.formatValor(dep.getQtdRecurso()) + "/" + Formatter.formatValor(dep.getQtdMaxRecurso()));
                textMinerio.setText(Formatter.formatValor(mineradora.getProdutividadeMaquinaMinerio())
                        + " kg/s (Max: " + Formatter.formatValor(mineradora.getProdutividadeMaquinaMinerioMax()) + " kg/s)");
                qtdMinerioRemovida.setText(Formatter.formatValor(dep.getQtdRemovida()));

                pbEnergia.setValue((int) (fon.getQtdRecurso() * 100 / fon.getQtdMaxRecurso()));

                pbEnergia.setString(Formatter.formatValor(fon.getQtdRecurso()) + "/" + Formatter.formatValor(fon.getQtdMaxRecurso()));
                textEnergia.setText(Formatter.formatValor(mineradora.getProdutividadeOperarioEnergia())
                        + " kw/s (Max: " + Formatter.formatValor(mineradora.getProdutividadeOperarioEnergia()) + " kw/s)");
                qtdEnergiaRemovida.setText(Formatter.formatValor(fon.getQtdRemovida()));
            }
        };

        worker.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        qtdMg = new javax.swing.JLabel();
        qtdMp = new javax.swing.JLabel();
        btnAddOperarioEnergia = new javax.swing.JButton();
        btnAddMaquinaGrande = new javax.swing.JButton();
        btnRemoveMaquinaGrande = new javax.swing.JButton();
        btnAddMaquinaPequena = new javax.swing.JButton();
        btnRemoveMaquinaPequena = new javax.swing.JButton();
        qtdOe = new javax.swing.JLabel();
        btnAddOperarioKg = new javax.swing.JButton();
        qtdOk = new javax.swing.JLabel();
        btnRemoveOperarioKg = new javax.swing.JButton();
        btnRemoveOperarioEnergia = new javax.swing.JButton();
        tgMg = new javax.swing.JToggleButton();
        tgMp = new javax.swing.JToggleButton();
        tgOe = new javax.swing.JToggleButton();
        tgOk = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pbMinerio = new javax.swing.JProgressBar();
        textEnergia = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pbEnergia = new javax.swing.JProgressBar();
        textMinerio = new javax.swing.JLabel();
        qtdMinerioRemovida = new javax.swing.JLabel();
        qtdEnergiaRemovida = new javax.swing.JLabel();
        addDeposito = new javax.swing.JButton();
        removeDeposito = new javax.swing.JButton();
        removeFonte = new javax.swing.JButton();
        addFonte = new javax.swing.JButton();
        pbDepositoNeed = new javax.swing.JProgressBar();
        pbEnergiaNeed = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mineradora");

        qtdMg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdMg.setText("0");

        qtdMp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdMp.setText("0");

        btnAddOperarioEnergia.setText("+ OE");
        btnAddOperarioEnergia.setMinimumSize(new java.awt.Dimension(59, 23));
        btnAddOperarioEnergia.setPreferredSize(new java.awt.Dimension(59, 23));
        btnAddOperarioEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOperarioEnergiaActionPerformed(evt);
            }
        });

        btnAddMaquinaGrande.setText("+ MG");
        btnAddMaquinaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMaquinaGrandeActionPerformed(evt);
            }
        });

        btnRemoveMaquinaGrande.setText("- MG");
        btnRemoveMaquinaGrande.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMaquinaGrandeActionPerformed(evt);
            }
        });

        btnAddMaquinaPequena.setText("+ MP");
        btnAddMaquinaPequena.setMinimumSize(new java.awt.Dimension(59, 23));
        btnAddMaquinaPequena.setPreferredSize(new java.awt.Dimension(59, 23));
        btnAddMaquinaPequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMaquinaPequenaActionPerformed(evt);
            }
        });

        btnRemoveMaquinaPequena.setText("- MP");
        btnRemoveMaquinaPequena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveMaquinaPequenaActionPerformed(evt);
            }
        });

        qtdOe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdOe.setText("0");

        btnAddOperarioKg.setText("+ OK");
        btnAddOperarioKg.setMinimumSize(new java.awt.Dimension(59, 23));
        btnAddOperarioKg.setPreferredSize(new java.awt.Dimension(59, 23));
        btnAddOperarioKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOperarioKgActionPerformed(evt);
            }
        });

        qtdOk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtdOk.setText("0");

        btnRemoveOperarioKg.setText("- OK");
        btnRemoveOperarioKg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOperarioKgActionPerformed(evt);
            }
        });

        btnRemoveOperarioEnergia.setText("- OE");
        btnRemoveOperarioEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveOperarioEnergiaActionPerformed(evt);
            }
        });

        tgMg.setText("ON");
        tgMg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgMgActionPerformed(evt);
            }
        });

        tgMp.setText("ON");
        tgMp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgMpActionPerformed(evt);
            }
        });

        tgOe.setText("OFF");
        tgOe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgOeActionPerformed(evt);
            }
        });

        tgOk.setText("ON");
        tgOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tgMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qtdMg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAddMaquinaGrande, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE))
                    .addComponent(btnRemoveMaquinaGrande, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRemoveMaquinaPequena, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qtdMp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddMaquinaPequena, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tgMp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qtdOe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddOperarioEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(btnRemoveOperarioEnergia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tgOe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddOperarioKg, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(qtdOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveOperarioKg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tgOk, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddMaquinaGrande)
                    .addComponent(btnAddMaquinaPequena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOperarioEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddOperarioKg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtdMg)
                    .addComponent(qtdMp)
                    .addComponent(qtdOe)
                    .addComponent(qtdOk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveMaquinaGrande)
                    .addComponent(btnRemoveMaquinaPequena)
                    .addComponent(btnRemoveOperarioEnergia)
                    .addComponent(btnRemoveOperarioKg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tgMg)
                    .addComponent(tgMp)
                    .addComponent(tgOe)
                    .addComponent(tgOk))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.setText("Energia:");

        pbMinerio.setForeground(new java.awt.Color(153, 153, 153));
        pbMinerio.setToolTipText("");
        pbMinerio.setValue(50);
        pbMinerio.setStringPainted(true);

        textEnergia.setText("1000 Kw/s");

        jLabel1.setText("Minério:");

        pbEnergia.setForeground(new java.awt.Color(0, 204, 255));
        pbEnergia.setToolTipText("");
        pbEnergia.setValue(50);
        pbEnergia.setStringPainted(true);

        textMinerio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textMinerio.setText("10 Kg/s");

        qtdMinerioRemovida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        qtdMinerioRemovida.setText("0");

        qtdEnergiaRemovida.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        qtdEnergiaRemovida.setText("0");

        addDeposito.setText("+");
        addDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDepositoActionPerformed(evt);
            }
        });

        removeDeposito.setText("-");
        removeDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDepositoActionPerformed(evt);
            }
        });

        removeFonte.setText("-");
        removeFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeFonteActionPerformed(evt);
            }
        });

        addFonte.setText("+");
        addFonte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFonteActionPerformed(evt);
            }
        });

        pbDepositoNeed.setForeground(new java.awt.Color(153, 153, 153));
        pbDepositoNeed.setToolTipText("");
        pbDepositoNeed.setValue(50);

        pbEnergiaNeed.setForeground(new java.awt.Color(153, 153, 153));
        pbEnergiaNeed.setToolTipText("");
        pbEnergiaNeed.setValue(50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtdMinerioRemovida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textMinerio))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(removeDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pbDepositoNeed, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pbMinerio, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(qtdEnergiaRemovida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(textEnergia))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(removeFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pbEnergiaNeed, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pbEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addFonte, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textMinerio)
                    .addComponent(qtdMinerioRemovida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbMinerio, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addDeposito)
                    .addComponent(removeDeposito))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbDepositoNeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textEnergia)
                    .addComponent(qtdEnergiaRemovida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pbEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeFonte)
                    .addComponent(addFonte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pbEnergiaNeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(404, 324));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMaquinaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMaquinaGrandeActionPerformed
        mineradora.addMaquina(new MaquinaGrande(mineradora.getDeposito(), mineradora.getFonte()));
        int qtd = 0;
        qtd = mineradora.getMaquinas().stream().filter((maquina) -> (maquina instanceof MaquinaGrande)).map((_item) -> 1).reduce(qtd, Integer::sum);
        qtdMg.setText(String.valueOf(qtd));
    }//GEN-LAST:event_btnAddMaquinaGrandeActionPerformed

    private void btnRemoveMaquinaGrandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMaquinaGrandeActionPerformed
        if (mineradora.removeMaquinaGrande()) {
            int qtd = 0;
            qtd = mineradora.getMaquinas().stream().filter((maquina) -> (maquina instanceof MaquinaGrande)).map((_item) -> 1).reduce(qtd, Integer::sum);
            qtdMg.setText(String.valueOf(qtd));
        }
    }//GEN-LAST:event_btnRemoveMaquinaGrandeActionPerformed

    private void btnAddMaquinaPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMaquinaPequenaActionPerformed
        mineradora.addMaquina(new MaquinaPequena(mineradora.getDeposito(), mineradora.getFonte()));
        int qtd = 0;
        qtd = mineradora.getMaquinas().stream().filter((maquina) -> (maquina instanceof MaquinaPequena)).map((_item) -> 1).reduce(qtd, Integer::sum);
        qtdMp.setText(String.valueOf(qtd));
    }//GEN-LAST:event_btnAddMaquinaPequenaActionPerformed

    private void btnRemoveMaquinaPequenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveMaquinaPequenaActionPerformed
        if (mineradora.removeMaquinaPequena()) {
            int qtd = 0;
            qtd = mineradora.getMaquinas().stream().filter((maquina) -> (maquina instanceof MaquinaPequena)).map((_item) -> 1).reduce(qtd, Integer::sum);
            qtdMp.setText(String.valueOf(qtd));
        }
    }//GEN-LAST:event_btnRemoveMaquinaPequenaActionPerformed

    private void btnAddOperarioEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOperarioEnergiaActionPerformed
        mineradora.addOperario(new OperarioEnergia(mineradora.getFonte()));
        int qtd = 0;
        qtd = mineradora.getOperarios().stream().filter((operario) -> (operario instanceof OperarioEnergia)).map((_item) -> 1).reduce(qtd, Integer::sum);
        qtdOe.setText(String.valueOf(qtd));
    }//GEN-LAST:event_btnAddOperarioEnergiaActionPerformed

    private void btnRemoveOperarioEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOperarioEnergiaActionPerformed
        if (mineradora.removeOperarioEnergia()) {
            int qtd = 0;
            qtd = mineradora.getOperarios().stream().filter((operario) -> (operario instanceof OperarioEnergia)).map((_item) -> 1).reduce(qtd, Integer::sum);
            qtdOe.setText(String.valueOf(qtd));
        }
    }//GEN-LAST:event_btnRemoveOperarioEnergiaActionPerformed

    private void btnAddOperarioKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOperarioKgActionPerformed
        mineradora.addOperario(new OperarioKg(mineradora.getDeposito()));
        int qtd = 0;
        qtd = mineradora.getOperarios().stream().filter((operario) -> (operario instanceof OperarioKg)).map((_item) -> 1).reduce(qtd, Integer::sum);
        qtdOk.setText(String.valueOf(qtd));
    }//GEN-LAST:event_btnAddOperarioKgActionPerformed

    private void btnRemoveOperarioKgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveOperarioKgActionPerformed
        if (mineradora.removeOperarioKg()) {
            int qtd = 0;
            qtd = mineradora.getOperarios().stream().filter((operario) -> (operario instanceof OperarioKg)).map((_item) -> 1).reduce(qtd, Integer::sum);
            qtdOk.setText(String.valueOf(qtd));
        }
    }//GEN-LAST:event_btnRemoveOperarioKgActionPerformed

    private void removeDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDepositoActionPerformed
        mineradora.getDeposito().downgrade();
    }//GEN-LAST:event_removeDepositoActionPerformed

    private void addDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDepositoActionPerformed
        mineradora.getDeposito().upgrade();
    }//GEN-LAST:event_addDepositoActionPerformed

    private void removeFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeFonteActionPerformed
        mineradora.getFonte().downgrade();
    }//GEN-LAST:event_removeFonteActionPerformed

    private void addFonteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFonteActionPerformed
        mineradora.getFonte().upgrade();
    }//GEN-LAST:event_addFonteActionPerformed

    private void tgMgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgMgActionPerformed
        boolean ativo = tgMg.isSelected();
        mineradora.getMaquinas().stream().filter((maquina) -> (maquina instanceof MaquinaGrande)).forEach((maquina) -> maquina.setAtivo(ativo));
    }//GEN-LAST:event_tgMgActionPerformed

    private void tgMpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgMpActionPerformed
        boolean ativo = tgMg.isSelected();
        mineradora.getMaquinas().stream().filter((maquina) -> (maquina instanceof MaquinaPequena)).forEach((maquina) -> maquina.setAtivo(ativo));
    }//GEN-LAST:event_tgMpActionPerformed

    private void tgOeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgOeActionPerformed
        boolean ativo = tgMg.isSelected();
        mineradora.getOperarios().stream().filter((operario) -> (operario instanceof OperarioEnergia)).forEach((operario) -> operario.setAtivo(ativo));
    }//GEN-LAST:event_tgOeActionPerformed

    private void tgOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgOkActionPerformed
        boolean ativo = tgMg.isSelected();
        mineradora.getOperarios().stream().filter((operario) -> (operario instanceof OperarioKg)).forEach((operario) -> operario.setAtivo(ativo));
    }//GEN-LAST:event_tgOkActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addDeposito;
    private javax.swing.JButton addFonte;
    private javax.swing.JButton btnAddMaquinaGrande;
    private javax.swing.JButton btnAddMaquinaPequena;
    private javax.swing.JButton btnAddOperarioEnergia;
    private javax.swing.JButton btnAddOperarioKg;
    private javax.swing.JButton btnRemoveMaquinaGrande;
    private javax.swing.JButton btnRemoveMaquinaPequena;
    private javax.swing.JButton btnRemoveOperarioEnergia;
    private javax.swing.JButton btnRemoveOperarioKg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar pbDepositoNeed;
    private javax.swing.JProgressBar pbEnergia;
    private javax.swing.JProgressBar pbEnergiaNeed;
    private javax.swing.JProgressBar pbMinerio;
    private javax.swing.JLabel qtdEnergiaRemovida;
    private javax.swing.JLabel qtdMg;
    private javax.swing.JLabel qtdMinerioRemovida;
    private javax.swing.JLabel qtdMp;
    private javax.swing.JLabel qtdOe;
    private javax.swing.JLabel qtdOk;
    private javax.swing.JButton removeDeposito;
    private javax.swing.JButton removeFonte;
    private javax.swing.JLabel textEnergia;
    private javax.swing.JLabel textMinerio;
    private javax.swing.JToggleButton tgMg;
    private javax.swing.JToggleButton tgMp;
    private javax.swing.JToggleButton tgOe;
    private javax.swing.JToggleButton tgOk;
    // End of variables declaration//GEN-END:variables
}
