angular.module('curso')
.config(['$stateProvider',
         '$urlRouterProvider',
         function($stateProvider,$urlRouterProvider){
                     $urlRouterProvider.otherwise('/cursos');
                     
                     $stateProvider
                           .state('cursos',{
                               url:'/cursos',
                               abstract:true,
                               templateUrl:'app/partials/cursos/cursos.html',
                               controller:'cursosController'
                            })
                            .state('cursos.lista',{
                               url:'',
                               templateUrl:'app/partials/cursos/lista.html',
                               controller:'cursosListaController'
                            })
                            .state('cursos.editar',{
                               url:'/editarCurso?id={idCurso}',
                               templateUrl:'app/partials/cursos/formulario.html',
                               controller:'cursosFormularioController'
                            })
                            .state('cursos.novo',{
                               url:'/novo',
                               templateUrl:'app/partials/cursos/formulario.html',
                               controller:'cursosFormularioController'
                            })
                            .state('professores',{
                               url:'/professores',
                               abstract:true,
                               templateUrl:'app/partials/professores/professores.html',
                               controller:'professoresController'
                            })
                            .state('professores.lista',{
                               url:'',
                               templateUrl:'app/partials/professores/lista-professores.html',
                               controller:'professoresListaController'
                            })
                            .state('professores.detalhe',{
                               url:'/detalhe?id={idProfessor}',
                               templateUrl:'app/partials/professores/detalhes.html',
                               controller:'professoresDetalheController'
                            })
                            .state('professores.editar',{
                               url:'/editar?id={idProfessor}',
                               templateUrl:'app/partials/professores/novo-professor.html',
                               controller:'professorNovoController'
                            })
                            .state('professores.novo',{
                               url:'/novo',
                               templateUrl:'app/partials/professores/novo-professor.html',
                               controller:'professorNovoController'
                            })
                            .state('certificacoes',{
                               url:'/certificacoes',
                               abstract:true,
                               templateUrl:'app/partials/certificacoes/certificacoes.html',
                               controller:'certificacoesController'
                            })
                            .state('certificacoes.lista',{
                               url:'',
                               templateUrl:'app/partials/certificacoes/lista.html',
                               controller:'certificacoesListaController'
                            })
                            .state('certificacoes.novo',{
                               url:'/novo',
                               templateUrl:'app/partials/certificacoes/formulario.html',
                               controller:'certificacoesNovoController'
                            })
                            .state('certificacoes.editar',{
                               url:'/editarCertificacao?id={idCertificacao}',
                               templateUrl:'app/partials/certificacoes/formulario.html',
                               controller:'certificacoesNovoController'
                            })
                            .state('turmas',{
                               url:'/turmas',
                               abstract:true,
                               templateUrl:'app/partials/turmas/turmas.html',
                               controller:'turmasController'
                            })
                            .state('turmas.lista',{
                               url:'',
                               templateUrl:'app/partials/turmas/lista.html',
                               controller:'turmasListaController'
                            })
                            .state('turmas.novo',{
                               url:'/novo',
                               templateUrl:'app/partials/turmas/formulario.html',
                               controller:'turmasNovoController'
                            })
                            .state('turmas.editar',{
                               url:'/editarTurmas?id={idTurma}',
                               templateUrl:'app/partials/turmas/formulario.html',
                               controller:'turmasNovoController'
                            })
                            .state('alunos',{
                               url:'/alunos',
                               abstract:true,
                               templateUrl:'app/partials/alunos/alunos.html',
                               controller:'alunosController'
                            })
                            .state('alunos.lista',{
                               url:'',
                               templateUrl:'app/partials/alunos/lista.html',
                               controller:'alunosListaController'
                            })
                            .state('alunos.novo',{
                               url:'/novo',
                               templateUrl:'app/partials/alunos/formulario.html',
                               controller:'alunosNovoController'
                            })
                            .state('alunos.editar',{
                               url:'/editarAluno?id={idAluno}',
                               templateUrl:'app/partials/alunos/formulario.html',
                               controller:'alunosNovoController'
                            })
                            ;
}]);

