/*
 * PanelCliente.java
 *
 * Created on 11 de Março de 2006, 10:42
 */

package br.org.soujava.teleentrega.gui;

import br.org.soujava.teleentrega.model.Cliente;
import br.org.soujava.teleentrega.persistence.Manager;

/**
 *
 * @author  vsenger
 */
public class PanelCliente extends javax.swing.JPanel {
  public TeleEntrega telaPai = null;
  private Cliente entity = null;
  /** Creates new form PanelCliente */
  public PanelCliente() {
    initComponents();
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    jLabel1 = new javax.swing.JLabel();
    textCodigo = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    textNome = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    textEndereco = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    textTelefones = new javax.swing.JTextField();
    buttonApply = new javax.swing.JButton();

    jLabel1.setText("C\u00f3digo");

    textCodigo.setEditable(false);

    jLabel2.setText("Nome");

    jLabel3.setText("Endere\u00e7o");

    jLabel4.setText("Telefones");

    buttonApply.setText("Apply");
    buttonApply.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonApplyActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(textTelefones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
          .add(textEndereco, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
          .add(layout.createSequentialGroup()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(jLabel1)
              .add(textCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
              .add(textNome, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
              .add(jLabel2)))
          .add(jLabel3)
          .add(jLabel4)
          .add(org.jdesktop.layout.GroupLayout.TRAILING, buttonApply))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(jLabel1)
          .add(jLabel2))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
          .add(textNome, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
          .add(textCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jLabel3)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(textEndereco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(jLabel4)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(textTelefones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
        .add(buttonApply)
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void buttonApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApplyActionPerformed
// TODO add your handling code here:
    Manager.getInstance().save(unbind());
    telaPai.populateTree();
  }//GEN-LAST:event_buttonApplyActionPerformed
  
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton buttonApply;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField textCodigo;
  private javax.swing.JTextField textEndereco;
  private javax.swing.JTextField textNome;
  private javax.swing.JTextField textTelefones;
  // End of variables declaration//GEN-END:variables
  public void bind(Cliente cliente) {
    this.entity = cliente;
    textCodigo.setText("" + cliente.getCodigo());
    textNome.setText(cliente.getNome());
    textEndereco.setText(cliente.getEndereco());
    textTelefones.setText(cliente.getTelefones());
  }
  public Cliente unbind() {
    entity.setEndereco(textEndereco.getText());
    entity.setNome(textNome.getText());
    entity.setTelefones(textTelefones.getText());
    return entity;
  }
}
